services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    image: sr-todo-web:latest
    ports:
      - "5005:5005"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      FLASK_SECRET: "change-me-in-prod"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data: